### PR TITLE
Detect if path is actually a directory

### PR DESCRIPTION
**Pull request by stevemao**
The Async version is not optimised. We need a promise version of isDirectory to do so.

### CODE REVIEW

**Comment by sindresorhus** [comment]
The async version needs to be fully async. The `is-directory` module is also faulty as it silences fs errors in the sync version.

I've made a better promise based module you can use instead:
https://github.com/sindresorhus/path-type

**Comment by stevemao** [comment]
nice. done

**Comment by sindresorhus** [comment]
Looks good. Thanks :)

**Comment by stevemao** [comment]
I just realise that variable names in the test is not good.

**Pull request closed without merging**
