### PR TITLE
Bump load-json-file

### PR DESCRIPTION
**Pull request by evocateur**
This picks up the line-numbers fix from https://github.com/sindresorhus/parse-json/pull/11

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests seem to be failing.

**Comment by evocateur** [comment]
Indeed, sorry about that, meant to follow up after I opened the PR.

**Comment by sindresorhus** [comment]
Ping :)

**Comment by evocateur** [comment]
This is no longer relevant, sorry for abandoning the drive-by PR

**Pull request closed without merging**
